// 1 GET_VAR → stack[0] = scope[0][2]
// 4 DUP → stack[1] = stack[0]
// 4 GET_PROP_NAME stack[1] ← stack[1]["reduce"]
// 7 GET_VAR → stack[2] = scope[1][8]
// 10 CALL func.apply(thisArg, [1 args]) → stack[0]
// 12 GET_VAR → stack[1] = scope[0][2]
// 14 GET_PROP_NAME stack[1] ← stack[1]["length"]
// 17 DIV stack[0] = stack[0] / stack[1]
// 18 RETURN stack[0]
