// 1 PUSH_UNDEFINED → stack[0] = undefined
// 2 GET_VAR → stack[1] = scope[1][2]
// 5 GET_VAR → stack[2] = scope[0][2]
// 8 GET_VAR → stack[3] = scope[0][3]
// 11 CALL func.apply(thisArg, [2 args]) → stack[0]
// 13 DUP → stack[1] = stack[0]
// 13 GET_PROP_NAME stack[1] ← stack[1]["then"]
// 15 PUSH_FUNCTION → stack[2] = function[75]
// 17 PUSH_FUNCTION → stack[3] = function[77]
// 20 CALL func.apply(thisArg, [2 args]) → stack[0]
// 22 DUP → stack[1] = stack[0]
// 22 GET_PROP_NAME stack[1] ← stack[1]["catch"]
// 24 PUSH_FUNCTION → stack[2] = function[78]
// 27 CALL func.apply(thisArg, [1 args]) → stack[0]
// 29 RETURN stack[0]
